### ISSUE TITLE
Avoid exposing RequestHeader

### ISSUE THREAD

**Issue by ivancesar-tt** [Splitit/Splitit.SDKs#2]
Original (from Assaf, google doc):

> Don't see any reason to expose RequestHeader as part of every request.

**Comment by ivancesar-tt** [comment]
Hm, not sure what you mean. Like not even generate that property within SDK? That could be a bit of a trouble to implement and support in all the languages appropriately. Current implementation uses that property and injects values supplied in constructor of API instance.

**Comment by assafbazar** [comment]
can it be changed to private in SDK  ? the client should never populate this element as the data there is  being populated as part of the InstallmentPlanApi constructor and should not be changed.

**Comment by ivancesar-tt** [comment]
It wasn't very trivial since languages are a bit different, and libraries are different for each, but I think I managed to handle it properly in all of the languages. 

I have no experience in PHP, and limited experience in TypeScript, but I think I found the way to get it done for those languages as well.

In most of the languages, headers are injected right before serialization.
