### ISSUE TITLE
Hide some properties/elements in SDK

### ISSUE THREAD

**Issue by ivancesar-tt** [Splitit/Splitit.SDKs#3]
Original from Assaf (google doc):

> - terminalref - should not be exposed in SDK
> - MoneyWithCurrecnyCode - rename to Money in SDK

**Comment by ivancesar-tt** [comment]
terminalref - Not exposed in API or just SDK?
Money - Probably possible to do automatically by changing the naming when generating the swagger JSON, but I need to look into it.

**Comment by assafbazar** [comment]
Remove the terminalRef from SDK , i would like also to remove from API but not sure i can it due to backward compatability (need to check who \ if anyone sends it )

**Comment by ivancesar-tt** [comment]
@assafbazar Unfortunately, "Money" already exists - see Splitit.BusinessService.DataContract.Entities.Installment.Money

Just figured this out when I was about to remove it.

**Comment by ivancesar-tt** [comment]
Removed TerminalRef, MoneyWithCurrencyCode stays the same due to naming conflict.

**Comment by assafbazar** [comment]
OK, good enough

**Comment by Splitit4Merchants** [comment]
@assafbazar  can't we not expose those objects just per the SDK? not good that merchants would get this info..
