### ISSUE TITLE
Provide additional information/documentation

### ISSUE THREAD

**Issue by ivancesar-tt** [Splitit/Splitit.SDKs#4]
From google doc:

> For each of the request objects, i think that we should provide some example code that sets the request object (starting with the InstallmentPlanCreate method)

**Comment by ivancesar-tt** [comment]
In each of the library, I updated a README a bit, and added examples for /Login, /Initiate, /Create.
If more will be needed, I can add.

For Typescript, readme is not generated automatically like in other languages, so needs to be copied directly from /sdk-gen/assets/typescript-fetch folder to appropriate output folder.

Assigned Ran to this issue, so when Jenkins is updated, it can be closed and optionally reopened later if more info is to be added.

**Comment by ranlandau** [comment]
Done in build process
