### ISSUE TITLE
Add Splitit SDK version as new key in http headers to our web-api 

### ISSUE THREAD

**Issue by assafbazar** [Splitit/Splitit.SDKs#6]
Please also add the SDK version as new key as part of the http headers

**Comment by Splitit4Merchants** [comment]
like this
Populate the request header of the /Create call with the following: "TouchPoint": {"Code": "HostedFields", "Version": "v1.0"}

taken from here: https://github.com/Splitit/Splitit.HostedFields/issues/2

**Comment by ivancesar-tt** [comment]
@Splitit4Merchants I didn't think those are related, I did implement adding proper HTTP headers to each request made from SDK, because SDK can be used separately from hosted fields.

Please verify what is the right direction here.

**Comment by Splitit4Merchants** [comment]
yes you are right Ivan

**Comment by ivancesar-tt** [comment]
Added Splitit-SDK header, with library name and version.
